import path from "path";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import fs from "fs";

const predefinedOrder: Record<string, string[]> = {
  overlay: [
    "§bOverlay Grafa §a1.21.X §fCzerwiec 2025.zip",
    "§dRóżowy §bOverlay Grafa §a1.21.X §fCzerwiec 2025.zip",
    "§bOverlay Grafa §a1.21 §fGrudzien 2024.zip",
    "§bOverlay Grafa §a1.19 §fCzerwiec 2022.zip",
    "§bOverlay Grafa §a1.19 §fLite.zip",
    "§bOverlay Grafa §a1.17 §fListopad 2021.zip",
    "§bOverlay Grafa §a1.16 §fMarzec 2021.zip",
    "§dRóżowy §6Overlay Grafa §a1.16 §fMarzec 2021.zip",
    "§bOverlay Grafa §a1.15 §fSierpień 2020.zip",
    "§dOverlay Grafa §a1.15 §fLuty 2020.zip",
    "§bOverlay Grafa §a1.14 §fSierpień 2020.zip",
    "§6Overlay Grafa §a1.14.4 §fStyczen 2020.zip",
    "§6Overlay Grafa §a1.14.4 §fGrudzien 2019.zip",
    "§6Overlay Grafa §a1.14.4 §fListopad 2019.zip",
    "§dOverlay Grafa §a1.13-14 §fLuty 2020.zip",
    "§bOverlay Grafa §a1.12 §fSierpień 2020.zip",
    "§bOverlay Grafa §a1.8 §fSierpień 2020.zip",
    "§dOverlay Grafa §a1.6-8 §fLuty 2020.zip",
    "§bStary Overlay Grafa §f1.9+.zip",
    "§bStary Overlay Grafa §f1.8.zip",
    "§bGUI - Grafs Edit.zip"
  ],
  ramki: [
    "§bRamki do rud §a1.19.zip",
    "§bRamki do rud §a1.17.zip",
    "§bRamki do rud §a1.16.zip",
    "§bRamki do rud §a1.15.zip",
    "§bRamki do rud  §a1.14.zip",
    "§bRamki do rud §a1.12.zip",
    "§bRamki do rud §a1.8.zip",
    "§dRóżowe §bRamki do rud.zip",
    "new.html"
  ],
  pozostale: [
    "§bLegacy Efficiency §a1.15.zip",
    "§eDisco Ziemniaki.zip",
    "§eNiska Tarcza.zip"
  ]
};

function generatePacksList() {
  const categories = ["overlay", "ramki", "pozostale"];
  const filesByCategory: Record<string, Array<{ display: string; file: string }>> = {
    overlay: [],
    ramki: [],
    pozostale: []
  };

  for (const category of categories) {
    const dirPath = path.resolve(__dirname, `public/pliki/${category}`);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
    
    const files = fs.readdirSync(dirPath);
    const fileStats = files
      .filter(file => file.endsWith(".zip") || file === "new.html")
      .map(file => {
        const filePath = path.join(dirPath, file);
        const stat = fs.statSync(filePath);
        return {
          file,
          mtime: stat.mtimeMs,
        };
      });

    // Sort by original list index if predefined, otherwise new files go to the top
    fileStats.sort((a, b) => {
      const order = predefinedOrder[category] || [];
      const indexA = order.indexOf(a.file);
      const indexB = order.indexOf(b.file);

      const hasA = indexA !== -1;
      const hasB = indexB !== -1;

      if (!hasA && !hasB) {
        return b.mtime - a.mtime;
      }
      if (!hasA) {
        return -1;
      }
      if (!hasB) {
        return 1;
      }
      return indexA - indexB;
    });

    filesByCategory[category] = fileStats.map(item => {
      let display = item.file.replace(/\.zip$/i, "");
      if (item.file === "new.html") {
        display = "Nowe Ramki do rud (tymczasowe przekierowanie)";
      } else {
        // Strip Minecraft color codes (e.g. §b, §a) for display name
        display = display.replace(/§./g, "").trim();
      }
      
      return {
        display,
        file: item.file
      };
    });
  }

  // Ensure new.html is appended to ramki if not found physically
  const hasNewHtml = filesByCategory.ramki.some((item) => item.file === "new.html");
  if (!hasNewHtml) {
    filesByCategory.ramki.push({
      display: "Nowe Ramki do rud (tymczasowe przekierowanie)",
      file: "new.html"
    });
  }

  const generatedPath = path.resolve(__dirname, "src/lib/generated-packs.ts");
  const fileContent = `// This file is auto-generated by the vite-plugin-generate-packs plugin.
// Do not edit this file manually.

export const generatedFilesByCategory = ${JSON.stringify(filesByCategory, null, 2)};
`;

  if (fs.existsSync(generatedPath)) {
    const existingContent = fs.readFileSync(generatedPath, "utf-8");
    if (existingContent === fileContent) {
      return;
    }
  }

  fs.writeFileSync(generatedPath, fileContent, "utf-8");
  console.log("[generate-packs] Successfully updated src/lib/generated-packs.ts");
}

function generatePacksPlugin() {
  return {
    name: "vite-plugin-generate-packs",
    buildStart() {
      generatePacksList();
    },
    configureServer(server: any) {
      const targetDirs = [
        path.resolve(__dirname, "public/pliki/overlay"),
        path.resolve(__dirname, "public/pliki/ramki"),
        path.resolve(__dirname, "public/pliki/pozostale")
      ];
      server.watcher.add(targetDirs);
      server.watcher.on("all", (event: string, filePath: string) => {
        if (targetDirs.some(dir => filePath.startsWith(dir))) {
          generatePacksList();
        }
      });
    }
  };
}

export default defineConfig({
  base: "./",
  plugins: [react(), generatePacksPlugin()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});